name: v3 Sync Tenant Repo to Main Repo 
on:
  workflow_dispatch:
    inputs:
      REPO:
        description: "Specify repo"
        required: true
      BRANCH:
        description: "Specify Branch"
        required: true
      PREFIX:
        description: "Specify prefix"
        required: true
      ACTION:
        description: "Specify Action pull / add"
        required: true
      commit:
        description: "Enter Commit message"
        required: true
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: Swa-DevOps/AEM-MAIN
          ref: refs/heads/scripts
      - name: subtree
        run: |
          chmod +x subtreev2.sh && bash subtreev2.sh $repo $branch $prefix $action $token $commit
        env:
          repo: ${{ inputs.REPO }}
          branch: ${{ inputs.BRANCH }}
          prefix: ${{ inputs.PREFIX }}
          action: ${{ inputs.ACTION }}
          token: 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
          commit: ${{ inputs.commit}}
